#!/bin/bash/						#dosya içeriği

PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbi/	#görev planlayıcısının(crontab) yolu,istediğimiz zaman aralıklarında çalışması için. 

																
	 
mesaj=$(curl http://api.openweathermap.org/data/2.5/weather\?id\=745044\&units\=metric\&APPID\=ed4b3f95a4b618d37d7a2d31c9fbb1cb |
jsawk 'return this.main.temp')				#burda this kodunun içerisinden jsawk yardımı ile sadece  hava durumunun sıcaklığını alıyoruz.
 

echo istanbul sıcaklık $mesaj				#echo ile istanbulun hava sıcakklığını yazar.

tarih=$(date +%c)					#burda gün,ayın kaçıncı günü,hangi ay,saat ve yılı tarih değişkenine atıyrouz.
echo $tarih						#echo ile tarihi yazdırır


t update " istanbulda sıcaklık: $mesaj $tarih		#tanımlı twitter hesabına  anlık aldığımız  hava sıcaklığını  t uygulaması ile twit attırıyoruz.
 
echo twit başarıyla atıldı                              #echo ile içeriği yazdırır. 
